routes:
  /:
    template: home
  /about/:
    template: about
  /contact/:
    template: contact
collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
