routes:
  /:
    template: 
      - home
  /home/:
    controller: channel
    template: 
      - intro
collections:
  /blog/:
    permalink: /blog/{slug}/
    template: 
      - index
  /about/:
    permalink: /about/
    template: 
      - about
taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/