routes:
  /:
    data: page.home
    template: home
  /about/:
    data: page.about
    template: about
  /schedule/:
    data: page.schedule
    template: schedule

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
